spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://61.132.229.11:2443/jswitch?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: jswitch
    password: jswitch@123
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      db-type: mysql
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      keep-alive: true
      async-init: true
      connection-properties: druid.stat.slowSqlMillis=2000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      client-type: jedis
      jedis:
        pool:
          # ???????????
          min-idle: 0
          # ???????????
          max-idle: 10
          # ????????????
          max-active: 20
          # #???????????????????????
          max-wait: -1
          enabled: true
          cluster:
            refresh:
              adaptive: true

